builds:
- main: .
  goos:
  - linux
  - darwin
  - windows
brews:
- tap:
    owner: onsd
    name: homebrew-tools
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  folder: Formula
  homepage: https://github.com/onsd/wd
