builds:
- main: .
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - '386'
    - amd64
    - arm64
brews:
- tap:
    owner: onsd
    name: homebrew-wd
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
